### PR TITLE
added better email check

### PR DESCRIPTION
**Pull request by Satindar31**
The previous one thought '!' was allowed in emails lol

### CODE REVIEW

**Comment by chill31** [comment]
thanks for the bug, I'll fix it myself

**Comment by Satindar31** [comment]
just accept mine -_-

**Comment by Satindar31** [comment]
💀

**Comment by Satindar31** [comment]
Yours also allows these:
-     Exclamation mark (!)
-     Number sign (#)
-     Dollar sign ($)
-     Percent sign (%)
-     Ampersand (&)
-     Tilde (~)

**Comment by chill31** [comment]
I'll fix it

**Comment by chill31** [comment]
fixed.
Thanks for reporting the bug though

**Comment by Satindar31** [comment]
Most professional conversation I had with a friend.

**Comment by chill31** [comment]
professional?

**Pull request closed without merging**
